Numpy used bcz its operations 10-100 times faster than list

Easy to apply operations as compare to lists like arithematic

In [2]:
import numpy as np

## 1D Array from list

In [3]:
python_list = [24,25,53,18,24,9,7,6,10]
array = np.array(python_list)
array

array([24, 25, 53, 18, 24,  9,  7,  6, 10])

## 2D  Array

In [9]:
python_list_of_lists = [[4,0,5],
                        [9,7,1],
                        [8,3,6]
    
]
array2 = np.array(python_list_of_lists)
array2


array([[4, 0, 5],
       [9, 7, 1],
       [8, 3, 6]])

In [11]:
array2.shape

(3, 3)

## Array of 0's

In [19]:
arr3=np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

## Random

In [20]:
np.random.random((1,2))

array([[0.91531605, 0.47100135]])

## Arrange

In [21]:
np.arange(-5,6)
     

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

## 3D Array  

In [23]:
array_1 = np.array([[1, 2],[3, 4]])
array_2 = np.array([[5, 6], [7, 8]])
array_3 = np.array([[9, 0], [6,9]])
array_3D = np.array([array_1, array_2, array_3])
array_3D
     

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[9, 0],
        [6, 9]]])

## 4D Array 

In [24]:
array_1_3D = np.array([array_1, array_2, array_3])
array_2_3D = np.array([array_1, array_3, array_2])
array_3_3D = np.array([array_2, array_3, array_1])
array_4_3D = np.array([array_2, array_1, array_3])
array_5_3D = np.array([array_3, array_1, array_2])

In [26]:
array_4D = np.array ( [array_1_3D, array_2_3D, array_3_3D, array_4_3D, array_5_3D])
array_4D

array([[[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]],

        [[9, 0],
         [6, 9]]],


       [[[1, 2],
         [3, 4]],

        [[9, 0],
         [6, 9]],

        [[5, 6],
         [7, 8]]],


       [[[5, 6],
         [7, 8]],

        [[9, 0],
         [6, 9]],

        [[1, 2],
         [3, 4]]],


       [[[5, 6],
         [7, 8]],

        [[1, 2],
         [3, 4]],

        [[9, 0],
         [6, 9]]],


       [[[9, 0],
         [6, 9]],

        [[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]]])

## Type Conversion 

In [27]:
boolean_array = np.array([[True, False],[True, False],], dtype = np.bool_)
boolean_array.astype(np.int32)

array([[1, 0],
       [1, 0]])

In [28]:
# type corecion
np.array(["hoo",23, 68.34, False]) #it converts all the values to string 

array(['hoo', '23', '68.34', 'False'], dtype='<U32')

## Arithmetic with NumPy Arrays 

In [39]:
# create two arrays with random numbers
arr1 = np.random.randint(1, 11, size=(3,3))
arr2 = np.random.randint(1, 11, size=(3,3))

# perform element-wise arithmetic operations
addition = arr1 + arr2
substraction = arr1 - arr2
multiplication = arr1 * arr2
division = arr1 / arr2 

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)
print("Element-wise addition:\n", addition)
print("Element-wise subtraction:\n", substraction)
print("Element-wise multiplication:\n", multiplication)
print("Element-wise division:\n", division)

Array 1:
 [[8 4 5]
 [7 8 8]
 [9 2 5]]
Array 2:
 [[ 9  4  5]
 [ 9  8  4]
 [ 3  1 10]]
Element-wise addition:
 [[17  8 10]
 [16 16 12]
 [12  3 15]]
Element-wise subtraction:
 [[-1  0  0]
 [-2  0  4]
 [ 6  1 -5]]
Element-wise multiplication:
 [[72 16 25]
 [63 64 32]
 [27  2 50]]
Element-wise division:
 [[0.88888889 1.         1.        ]
 [0.77777778 1.         2.        ]
 [3.         2.         0.5       ]]


In [49]:
power= arr1**arr2
print("Element-wise division:\n",power)

np.power(arr1,arr2)

Element-wise division:
 [[134217728       256      3125]
 [ 40353607  16777216      4096]
 [      729         2   9765625]]


array([[134217728,       256,      3125],
       [ 40353607,  16777216,      4096],
       [      729,         2,   9765625]], dtype=int32)

In [66]:
arr_T = arr1.T #column becomes row 
arr_dot = np.dot (arr1 , arr_T)
arr_exp = np.exp(arr1)

print("Original array:\n", arr1)
print("Transpose:\n", arr_T)
print("Dot product with transpose:\n", arr_dot)
print("Element-wise exponential:\n", arr_exp)

Original array:
 [[8 4 5]
 [7 8 8]
 [9 2 5]]
Transpose:
 [[8 7 9]
 [4 8 2]
 [5 8 5]]
Dot product with transpose:
 [[105 128 105]
 [128 177 119]
 [105 119 110]]
Element-wise exponential:
 [[2.98095799e+03 5.45981500e+01 1.48413159e+02]
 [1.09663316e+03 2.98095799e+03 2.98095799e+03]
 [8.10308393e+03 7.38905610e+00 1.48413159e+02]]


## Shaping 

In [67]:
arrl=np.random.randint(0,20, size=(2,3))
arrl

array([[ 6, 18,  4],
       [ 0, 14, 19]])

In [68]:
arrl.flatten()

array([ 6, 18,  4,  0, 14, 19])

In [69]:
arrl.reshape(3,2)

array([[ 6, 18],
       [ 4,  0],
       [14, 19]])

## Basic Indexing and Slicing in numpy 

**Indexing** 

In [70]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[2])  

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2[1, 2])  

3
6


**Slicing**

In [82]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1:4])  # 2nd to 4th position

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2[0:2, 1:3]) #ROW , COLUMN  ROW= FIRST 2  COLUMN=2ND,3RD (1:3) IF 2ND ONLY (1:2)

[2 3 4]
[[2 3]
 [5 6]]


**Boolean Indexing**

In [85]:
#using conditions
arr = np.array([1, 2, 3, 4, 5])
print(arr[arr > 3])  

arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2[arr2 > 5])  

[4 5]
[6 7 8 9]


In [ ]:
# Create a 2D NumPy array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Compute the sum of all elements in the array
print("Sum:", np.sum(arr))

# Compute the mean of all elements in the array
print("Mean:", np.mean(arr))

# Compute the standard deviation of all elements in the array
print("Standard deviation:", np.std(arr))

# Compute the minimum value of all elements in the array
print("Minimum:", np.min(arr))

# Compute the maximum value of all elements in the array
print("Maximum:", np.max(arr))

# Compute the index of the minimum value in the array
print("Index of minimum:", np.argmin(arr))

# Compute the index of the maximum value in the array
print("Index of maximum:", np.argmax(arr))

# Compute the median value of all elements in the array
print("Median:", np.median(arr))

# Compute the 25th and 75th percentiles of all elements in the array
print("25th percentile:", np.percentile(arr, 25))
print("75th percentile:", np.percentile(arr, 75))

# Compute a histogram of the values in the array using 3 bins
hist, bins = np.histogram(arr, bins=3)
print("Histogram:", hist)
print("Bins:", bins)