Broadcasting allows to perform element-wise operations on arrays with different shapes, without having to explicitly reshape or pad the arrays.

Can be done if one of the dimesnion is missing like arr(4,3)+arr(4,)

**Adding Two Arrays with Different Sizes**

In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4])

c = a + b
print(c)
     

[5 6 7]


**Adding Two Arrays with Different Number of Dimensions**

In [11]:
a = np.array([1, 2, 3])  #(3,)
b = np.array([[4, 5, 6], [7, 8, 9]]) #(2,3)

c = a[:, np.newaxis] + b.T  # both transposed 
print(c)
     

[[ 5  8]
 [ 7 10]
 [ 9 12]]


In [12]:
a[:,np.newaxis]

array([[1],
       [2],
       [3]])

**Multiplying Two Arrays with Different Shapes**

In [14]:
a = np.array([[1], [2], [3]])    #(3,1)
b = np.array([4, 5, 6]) # (3,)

c = a * b
print(c)

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


**Computing Outer Product of Two Arrays**

In [16]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.outer(a, b)
print(c)


[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


**Applying Arithematics directly to an array**

In [21]:
a=np.array([1,2,3])

c = a + 2
d = a - 1
e = a * 2
f = a / 2
print("Addition:",c)
print("Subtraction:",d)
print("Multiplication:",e)
print("Division:",f)

Addition: [3 4 5]
Subtraction: [0 1 2]
Multiplication: [2 4 6]
Division: [0.5 1.  1.5]


**Broadcasting in Higher Dimensions**

In [22]:
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])    # (2,2,2)
b = np.array([1, 2]) # (2,)

c = a + b[:, np.newaxis, np.newaxis]
print(c)

[[[ 2  3]
  [ 4  5]]

 [[ 7  8]
  [ 9 10]]]


In [25]:
b[:, np.newaxis, np.newaxis]

array([[[1]],

       [[2]]])